Feature/#37 display change of balance
se2-monopoly-ss20-v2/monopoly pull request #38
Opened 2020-05-26 16:31 UTC by SgtGraf

Player will now get an information when their balance is updated.
See attachement

![image](https://user-images.githubusercontent.com/58831256/82926206-20e89d80-9f7f-11ea-89f4-d84659db7a67.png)

2020-05-26 17:38 UTC, dermutzh requested changes
Just those two small comments. Fix them and feel free to merge.

2020-05-26 17:38 UTC, dermutzh commented on app/src/main/java/com/ss20/se2/monopoly/view/GameboardActivity.java
> +		if (oldBalance-newBalance == 0){
Use `difference` instead of `oldBalance-newBalance`

2020-05-26 17:38 UTC, dermutzh commented on app/src/main/java/com/ss20/se2/monopoly/view/GameboardActivity.java
> +			updateBalance.setText("$" + difference);
add `+` before $ so the User is aware that his balance has been increased. And that we have the same "Look" like in the else cond below.

2020-05-26 17:57 UTC, merged

2020-05-26 18:04 UTC, SgtGraf commented
Thank your :)

2020-05-27 10:30 UTC, SgtGraf commented
closes #37